### PR TITLE
Bookstore: Use Redux in React components.

### PR DESCRIPTION
**Pull request by NayanKaran**
Hi,

I have implemented the following project requirements.

### Project requirements
- First of all - make sure that you keep state immutable in reducers!
- Secondly, change the default state in your books reducer from an empty array to an array with a few books. One of the goals is to display them in your React components.
- Import Redux `Provider` and your store in the main component of your React app.
- Connect your app to the Redux store.
- Make sure that list of books displays books from Redux store.
    - Use `useSelector` to consume the state.
- In your React component responsible for adding new books, add functionality for "Add new" button click:
     - Import Redux `useDispatch`.
     - Set the data inputs in the local React state (set *title* and *author*  - NOTE: *categories* and *comments* are NOT part of this step). 
     - Once your new book object is ready to be submitted to Redux store, dispatch a corresponding action (import Action Creator that you created before and use it here).
- In your React component responsible for removing books, add a functionality for "Remove" button click:
    - Import Redux `useDispatch`.
    - Dispatch a corresponding action (import Action Creator that you created before and use it here).
- In your React component responsible for categories, add a functionality for "Check status" button click:
    - Import Redux `useDispatch`.
    - Dispatch a corresponding action (import Action Creator that you created before and use it here).

### CODE REVIEW

**Review by medaminedev66 — CHANGES_REQUESTED** [review]
Hi @NayanKaran 😃, :wave:, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- The repo looks professional
- Redux store is used to display books
- The components were made to dispatch actions.


## Required Changes ♻️
- [x] Please make sure that the state is immutable in all reducers (changes should be made on a copy of an array). Immutability of redux state is necessary since it allows detecting redux state changes in an efficient manner. This implies that whenever we want to modify a redux state, we must create a new copy of it and do modifications to that copy - which then becomes the new redux state.
Check out this [link ](https://stackoverflow.com/questions/39343700/why-immutable-state-with-redux) to learn why redux state should be immutable.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by NayanKaran** [comment]
Hi @medaminedev66,

[Redux Toolkit's `createReducer `and `createSlice `automatically use Immer internally to let you write simpler immutable update logic using "mutating" syntax. This helps simplify most reducer implementations.](https://redux-toolkit.js.org/usage/immer-reducers#:~:text=Redux%20Toolkit%27s%20createReducer%20and%20createSlice%20automatically%20use%20Immer%20internally%20to%20let%20you%20write%20simpler%20immutable%20update%20logic%20using%20%22mutating%22%20syntax.%20This%20helps%20simplify%20most%20reducer%20implementations.)

**Review by dasileker — APPROVED** [review]
### **Hi @NayanKaran,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by nicupop729 — COMMENTED** [review]
Hello @NayanKaran 👋,

_This is an additional review as a result of the second opinion request._

Nice implementation of the project requirements! Congrats! :clap: 

I am glad to see that your milestone is sorted out and that your PR is approved!
The Second Opinion Review is not necessary anymore!

Keep rocking 🚀!

**Pull request merged**
